# Terraform Backend Configuration - Generated by script

#### Used with: terraform init -backend-config=backend.config.tfvars ####

bucket         = "placeholder"
key            = "placeholder"
region         = "us-east-1"
dynamodb_table = "placeholder"
encrypt        = true