global:
  region: us-east-1
  environment: prod
  customer: private-env
  project: frontegg-private-env
settings:
  vpc:
    enabled: false
    vpc_id: "vpc-0000"
    cidr: "10.0.0.0/16"
    subnets:
      private: [subnet-0000000000000000,subnet-0100000000000000,subnet-0200000000000000]
      intra: []
  s3:
    enabled: true
  secretsManager:
    secrets:
      recovery_window_in_days: 7
  msk:
    config:
      enabled: false
      version: "3.6.0"
      number_of_broker_nodes: 3
      volume_size: 500
      broker_node_instance_type: "kafka.m5.large"
      scaling_max_capacity: 500
      scaling_target_value: 60
      enable_msk_logs: true
      msk_bootstrap_brokers_plaintext: "broker-1.amazonaws.com:9092,broker-2.amazonaws.com:9092,broker-3.amazonaws.com:9092"
      msk_bootstrap_brokers_sasl_iam: ""
      msk_bootstrap_brokers_sasl_scram: ""
      msk_bootstrap_brokers_tls: ""
      username: ""
      password: ""
      authentication:
        unauthenticated: true
        sasl:
          iam: false
          scram: false
    connector:
      debezium:
        enabled: false
  mysql:
    config:
      enabled: false
      family: "mysql8.0"
      major_engine_version: "8.0"
      engine_version: "8.0.40"
      instance_class: "db.t3.medium"
      storage:
        type: "gp3"
        allocated: 100
        max_allocated: 500
      port: 3306
      multi_az: false
      maintenance_window: "sun:04:00-sun:05:00"
      backup_window: "03:00-04:00"
      backup_retention_period: 7
      create_cloudwatch_log_group: true
      enabled_cloudwatch_logs_exports:
        - general
        - error
        - slowquery
        - audit
      skip_final_snapshot: false
      deletion_protection: true
      performance_insights_enabled: true
      performance_insights_retention_period: 7
      endpoint: "mysql-endpoint.amazonaws.com"
      username: "username"
      password: "password"
  redis:
    config:
      enabled: false
      family: "redis7"
      engine_version: "7.0"
      node_type: "cache.t3.medium"
      num_cache_clusters: 2
      endpoint: "redis-endpoint.amazonaws.com:6379"
      username: "username"
      password: "password"
      port: "6379"
      tls: true
  mongo:
    config:
      endpoint: "mongodb://mongodb-endpoint.amazonaws.com"
      username: "username"
      password: "password"
  eks:
    config:
      enabled: false
      cluster:
        name: private-env-prod-eks
        version: "1.32"
        endpoint_public_access: false
        endpoint_public_access_cidrs:
          - "0.0.0.0/0"
      managed_node_groups:
        capacity_type: "ON_DEMAND"
        instance_types:
          - m5.large
          - m5.xlarge
          - m5.2xlarge
          - m5.4xlarge
          - m5d.large
          - m6i.large
        min_size: 2
        max_size: 5
        desired_size: 3
      managed_node_groups_defaults:
        instance_types:
          - m6i.large
          - m6i.xlarge
          - m6i.2xlarge
          - m6i.4xlarge
          - m6i.8xlarge
          - m5.large
          - m5.xlarge
          - m5.2xlarge
          - m5.4xlarge
          - m5.8xlarge
          - m5d.large
          - m5d.xlarge
          - m5d.2xlarge
          - m5d.4xlarge
          - m5d.8xlarge
      auto_mode:
        enabled: false
  external_secrets:
    config:
      enabled: true
      version: "0.15.0"
      replicaCount: 2
      concurrent: 10





# --- Auto Generated ---
# generation timestamp: 2025-06-15T20:48:21.227446+00:00
# generated by: eyal.tam
# generated on host: F-eyal-tam