global:
  region: us-east-1
  environment: prod
  customer: private-env
  project: frontegg-private-env
settings:
  vpc:
    enabled: false
    vpc_id: "vpc-0ad20d3162e42d15c"
    cidr: "10.0.0.0/16"
    subnets:
      private:
        [
          subnet-05b2d6ce16c9d1a4a,
          subnet-000a9c5c5d923dc2d,
          subnet-0a18b1a1e33568594,
        ]
      intra:
        [
          subnet-0e9f0431456770ec6,
          subnet-0f5d207df8c33382d,
          subnet-03fc8cdcf0574bb94,
        ]
  s3:
    enabled: true
    force_destroy_buckets: true
  secretsManager:
    secrets:
      recovery_window_in_days: 0
  msk:
    config:
      enabled: true
      version: "3.6.0"
      number_of_broker_nodes: 3
      volume_size: 500
      broker_node_instance_type: "kafka.m5.large"
      scaling_max_capacity: 500
      scaling_target_value: 60
      enable_msk_logs: true
      msk_bootstrap_brokers_plaintext: "b-1.prodmsk360.b35ne2.c1.kafka.us-east-1.amazonaws.com:9092,b-2.prodmsk360.b35ne2.c1.kafka.us-east-1.amazonaws.com:9092,b-3.prodmsk360.b35ne2.c1.kafka.us-east-1.amazonaws.com:9092"
      msk_bootstrap_brokers_sasl_iam: ""
      msk_bootstrap_brokers_sasl_scram: ""
      msk_bootstrap_brokers_tls: ""
      encryption_in_transit_client_broker: "PLAINTEXT" #"TLS_PLAINTEXT"
      username: ""
      password: ""
      authentication:
        unauthenticated: true
        sasl:
          iam: false
          scram: false
    connector:
      debezium:
        enabled: true
  mysql:
    config:
      enabled: true
      family: "mysql8.0"
      major_engine_version: "8.0"
      engine_version: "8.0.40"
      instance_class: "db.t3.medium"
      storage:
        type: "gp3"
        allocated: 100
        max_allocated: 500
      port: 3306
      multi_az: false
      maintenance_window: "sun:04:00-sun:05:00"
      backup_window: "03:00-04:00"
      backup_retention_period: 7
      create_cloudwatch_log_group: true
      enabled_cloudwatch_logs_exports:
        - general
        - error
        - slowquery
        - audit
      skip_final_snapshot: true
      deletion_protection: false
      performance_insights_enabled: true
      performance_insights_retention_period: 7
      endpoint: "prod-mysql8-0-40.c1hrwrvemzzh.us-east-1.rds.amazonaws.com"
      username: "root"
      password: ""
  redis:
    config:
      enabled: true
      family: "redis7"
      engine_version: "7.0"
      node_type: "cache.t3.medium"
      num_cache_clusters: 2
      endpoint: "prod-7-0-redis.so7c2d.ng.0001.use1.cache.amazonaws.com:6379"
      transit_encryption_enabled: false
      username: ""
      password: ""
      port: "6379"
      tls: true
  mongo:
    config:
      endpoint: "mongodb://mongodb"
      username: "placeholder"
      password: "placeholder"
  eks:
    config:
      enabled: true
      cluster:
        name: private-env-prod-eks
        version: "1.32"
        endpoint_public_access: true
        endpoint_public_access_cidrs:
          - "0.0.0.0/0"
      managed_node_groups:
        capacity_type: "SPOT"
        instance_types:
          - m5.large
          - m5.xlarge
          - m5.2xlarge
          - m5.4xlarge
          - m5d.large
          - m6i.large
        min_size: 2
        max_size: 18
        desired_size: 18
      managed_node_groups_defaults:
        instance_types:
          - m6i.large
          - m6i.xlarge
          - m6i.2xlarge
          - m6i.4xlarge
          - m6i.8xlarge
          - m5.large
          - m5.xlarge
          - m5.2xlarge
          - m5.4xlarge
          - m5.8xlarge
          - m5d.large
          - m5d.xlarge
          - m5d.2xlarge
          - m5d.4xlarge
          - m5d.8xlarge
      auto_mode:
        enabled: false
  external_secrets:
    config:
      enabled: true
      version: "0.15.0"
      replicaCount: 2
      concurrent: 10
# --- Auto Generated ---
# generation timestamp: 2025-06-15T20:48:21.227446+00:00
# generated by: eyal.tam
# generated on host: F-eyal-tam
