{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.externalSecrets.clusterSecretStore.name }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.global.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.externalSecrets.clusterSecretStore.serviceAccount.name }}
            namespace: {{ .Values.externalSecrets.clusterSecretStore.serviceAccount.namespace }}
{{- end }} 