name: Delete Customer Environment

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "destroy" to confirm you want to destroy the environment.'
        required: true
        default: ''

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'destroy' && contains(fromJSON('["eyaltam1971"]'), github.actor)
    name: Terraform Destroy
    env:
      EKS_CLUSTER_NAME: private-env-prod-eks
      AWS_REGION: us-east-1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::109940070146:role/cross-account-admin-assume-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Kubeconfig
        run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }} || true

      - name: Uninstall Frontegg Core Services
        run: |
          helm uninstall frontegg-core-services --namespace frontegg || true

      - name: Uninstall Frontegg Dashboard
        run: |
          helm uninstall frontegg-dashboard --namespace frontegg || true

      - name: Check if all pods are deleted
        run: |
          for i in {1..10}; do
            echo "Iteration $i: Checking pods in frontegg namespace..."
            kubectl get pods --namespace frontegg
            PODS=$(kubectl get pods --namespace frontegg --no-headers 2>/dev/null | wc -l)
            if [ "$PODS" -eq 0 ]; then
              echo "All pods are deleted."
              exit 0
            fi
            echo "Pods still exist. Waiting 10 seconds before next check..."
            sleep 10
          done
          echo "There are still pods running in the frontegg namespace after waiting. Please check and try again."
          exit 1

      - name: Uninstall NGINX Ingress Controller
        run: |
          helm uninstall nginx-ingress --namespace ingress-nginx || true

      - name: Uninstall ExternalDNS
        run: |
          helm uninstall external-dns --namespace external-dns || true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.2

      - name: Terraform Init
        id: init
        run: |
          terraform init \
            -backend-config="bucket=frontegg-tfstate-109940070146-us-east-1" \
            -backend-config="key=tf-state/frontegg/private-env/terraform.tfstate" \
            -backend-config="region=us-east-1" \
            -backend-config="dynamodb_table=frontegg-terraform-state-lock" \
            -backend-config="encrypt=true"

      - name: Terraform Destroy
        run: |
          n=0
          until [ "$n" -ge 3 ]
          do
            terraform destroy -auto-approve && break
            n=$((n+1))
            echo "Terraform destroy failed. Retrying ($n/3) in 10 seconds..."
            sleep 10
          done 