name: Frontegg Customer Environment - TF Apply

on:
  workflow_dispatch:
  push:
    paths:
      - 'frontegg-customer-env/**'
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Terraform Apply
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::109940070146:role/cross-account-admin-assume-role
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        id: init
        run: terraform init \
          -backend-config="bucket=frontegg-tfstate-109940070146-us-east-1" \
          -backend-config="key=tf-state/frontegg/terraform.tfstate" \
          -backend-config="region=us-east-1" \
          -backend-config="dynamodb_table=frontegg-terraform-state-lock" \
          -backend-config="encrypt=true"
        working-directory: ./frontegg-customer-env

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        working-directory: ./frontegg-customer-env

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./frontegg-customer-env

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Add Frontegg Helm repo
        run: helm repo add frontegg https://frontegg.github.io/helm-charts && helm repo update

      - name: Helm Dependency Update
        run: helm dependency update
        working-directory: ./frontegg-customer-env

      - name: Deploy Frontegg Core Services
        run: helm upgrade --install frontegg-core-services frontegg/frontegg-core-services --namespace frontegg --create-namespace

      - name: Deploy Frontegg Dashboard
        run: helm upgrade --install frontegg-dashboard frontegg/frontegg-dashboard --namespace frontegg 