name:  Create Customer Environment

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    name: Terraform Apply
    if: contains(fromJSON('["eyaltam1971"]'), github.actor)
    env:
      AWS_REGION: us-east-1
      AWS_ASSUME_ROLE_ARN: arn:aws:iam::109940070146:role/cross-account-admin-assume-role
      EKS_CLUSTER_NAME: private-env-prod-eks
      EKS_ADMIN_PRINCIPAL_ARN: arn:aws:iam::109940070146:role/AWSReservedSSO_AdministratorAccess_a105bdd30189cd8e
      EKS_ADMIN_POLICY_ARN: arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy
      TF_STATE_BUCKET: frontegg-tfstate-109940070146-us-east-1
      TF_STATE_KEY: tf-state/frontegg/private-env/terraform.tfstate
      TF_STATE_LOCK_TABLE: frontegg-terraform-state-lock
      GLOBAL_ENV_ID: prod-frontegg-private-deployment-main-secret
      SETUP_JOB_EMAIL: devops@frontegg.com
      SETUP_JOB_PASSWORD: '123456'
      SETUP_JOB_SENDER_EMAIL: devops+onprem@frontegg.com
      API_GATEWAY_URL: https://api.frontegg.com
      VENDOR_HOST: frontegg.com
      OPA_POLICY_BUCKET: frontegg-prod-opa-policy
      PORTAL_URL: https://portal.frontegg.com
      CORS_ORIGIN: https://app.frontegg.com
      API_GATEWAY_IGNORED_HOSTS: localhost
      VENDORS_SERVICE_VENDORS_DOMAIN: frontegg.com
      CROSS_ACCOUNT_ADMIN_ASSUME_ROLE_ARN: arn:aws:iam::109940070146:role/cross-account-admin-assume-role
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ASSUME_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.2

      - name: Terraform Init
        id: init
        run: |
          terraform init \
            -backend-config="bucket=${{ env.TF_STATE_BUCKET }}" \
            -backend-config="key=${{ env.TF_STATE_KEY }}" \
            -backend-config="region=${{ env.AWS_REGION }}" \
            -backend-config="dynamodb_table=${{ env.TF_STATE_LOCK_TABLE }}" \
            -backend-config="encrypt=true"

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Setup Kubeconfig
        run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      - name: Set Terraform Outputs
        id: tf_outputs
        run: |
          terraform output -json msk_output > /tmp/msk_output.json
          echo "Raw MSK output from file:"
          cat /tmp/msk_output.json
          
          # Clean the file to only include the JSON object
          grep '^{' /tmp/msk_output.json > /tmp/msk_output_clean.json
          
          echo "Cleaned MSK output:"
          cat /tmp/msk_output_clean.json
          
          brokers=""
          if [[ -s /tmp/msk_output_clean.json ]] && [[ $(cat /tmp/msk_output_clean.json) != "null" ]]; then
            brokers_raw=$(jq -r .bootstrap_brokers_plaintext /tmp/msk_output_clean.json)
            echo "Extracted brokers (raw): $brokers_raw"
            # Escape commas for Helm --set command
            brokers=$(echo "$brokers_raw" | sed 's/,/\\,/g')
          fi
          
          echo "Extracted brokers (escaped for Helm): $brokers"
          echo "msk_bootstrap_brokers=$brokers" >> $GITHUB_OUTPUT

      - name: List EKS Access Entries
        run: |
          aws eks list-access-entries --cluster-name ${{ env.EKS_CLUSTER_NAME }}

      - name: Create EKS Access Entries
        run: |
          # aws eks create-access-entry \
          #   --cluster-name ${{ env.EKS_CLUSTER_NAME }} \
          #   --principal-arn "${{ env.EKS_ADMIN_PRINCIPAL_ARN }}" \
          #   --region ${{ env.AWS_REGION }}

          aws eks create-access-entry \
            --cluster-name ${{ env.EKS_CLUSTER_NAME }} \
            --principal-arn "${{ env.CROSS_ACCOUNT_ADMIN_ASSUME_ROLE_ARN }}" \
            --region ${{ env.AWS_REGION }}

      - name: Grant EKS Admin Access to SSO Role
        run: |
          # aws eks associate-access-policy \
          #   --cluster-name ${{ env.EKS_CLUSTER_NAME }} \
          #   --principal-arn "${{ env.EKS_ADMIN_PRINCIPAL_ARN }}" \
          #   --access-scope type=cluster \
          #   --policy-arn ${{ env.EKS_ADMIN_POLICY_ARN }} \
          #   --region ${{ env.AWS_REGION }}

          aws eks associate-access-policy \
            --cluster-name ${{ env.EKS_CLUSTER_NAME }} \
            --principal-arn "${{ env.CROSS_ACCOUNT_ADMIN_ASSUME_ROLE_ARN }}" \
            --access-scope type=cluster \
            --policy-arn ${{ env.EKS_ADMIN_POLICY_ARN }} \
            --region ${{ env.AWS_REGION }}
      

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Deploy MongoDB
        run: |
          helm upgrade --install mongodb ./helm/mongodb6 \
            --namespace frontegg \
            --create-namespace \
            --values ./helm/mongodb6/values.yaml

      - name: Pull and Patch Frontegg Core Services Chart
        run: |
          helm pull frontegg/frontegg-core-services --untar --destination . --devel
          sed -i 's/| tpl .region //g' ./frontegg-core-services/templates/config-center.yaml

      - name: Deploy Frontegg Core Services
        run: |
          helm upgrade --install frontegg-core-services ./frontegg-core-services \
            --namespace frontegg \
            --create-namespace \
            --devel \
            --set global.envId=${{ env.GLOBAL_ENV_ID }} \
            --set "debezium.bootstrapServers=${{ steps.tf_outputs.outputs.msk_bootstrap_brokers }}" \
            --set environmentSetupJob.email=${{ env.SETUP_JOB_EMAIL }} \
            --set environmentSetupJob.password=${{ env.SETUP_JOB_PASSWORD }} \
            --set environmentSetupJob.senderEmail=${{ env.SETUP_JOB_SENDER_EMAIL }} \
            --set configCenter.frontegg.services.apiGatewayUrl=${{ env.API_GATEWAY_URL }} \
            --set configCenter.frontegg.services.fronteggVendorHost=${{ env.VENDOR_HOST }} \
            --set configCenter.externalServices.aws.region=${{ env.AWS_REGION }} \
            --set configCenter.frontegg.applications.entitlements.opaPolicyBucket=${{ env.OPA_POLICY_BUCKET }} \
            --set configCenter.frontegg.general.portalUrl=${{ env.PORTAL_URL }} \
            --set configCenter.frontegg.general.corsOrigin=${{ env.CORS_ORIGIN }} \
            --set configCenter.frontegg.applications.apiGateway.apiGatewayIgnoredHosts=${{ env.API_GATEWAY_IGNORED_HOSTS }} \
            --set configCenter.frontegg.applications.vendors.vendorsServiceVendorsDomain=${{ env.VENDORS_SERVICE_VENDORS_DOMAIN }}

      - name: Deploy Frontegg Dashboard
        run: |
          helm upgrade --install frontegg-dashboard frontegg/frontegg-dashboard \
            --namespace frontegg \
            --devel \
            --set global.envId=${{ env.GLOBAL_ENV_ID }}